{"time":"2025-08-06T18:14:22.6996034-04:00","level":"INFO","msg":"stream: starting","core version":"0.21.0"}
{"time":"2025-08-06T18:14:23.4650114-04:00","level":"INFO","msg":"stream: created new stream","id":"dghsc6tj"}
{"time":"2025-08-06T18:14:23.4657213-04:00","level":"INFO","msg":"stream: started","id":"dghsc6tj"}
{"time":"2025-08-06T18:14:23.4657213-04:00","level":"INFO","msg":"handler: started","stream_id":"dghsc6tj"}
{"time":"2025-08-06T18:14:23.4657213-04:00","level":"INFO","msg":"writer: Do: started","stream_id":"dghsc6tj"}
{"time":"2025-08-06T18:14:23.4657213-04:00","level":"INFO","msg":"sender: started","stream_id":"dghsc6tj"}
{"time":"2025-08-06T19:03:59.813285-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.250.108.120:49846->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T19:04:00.4694607-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/tobiassafie-drexel-university/GBM-LSTM-lr-hiddenDim-dropout/dghsc6tj/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T19:04:22.9001921-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T19:04:23.6017902-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/tobiassafie-drexel-university/GBM-LSTM-lr-hiddenDim-dropout/dghsc6tj/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T19:08:44.5012315-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/tobiassafie-drexel-university/GBM-LSTM-lr-hiddenDim-dropout/dghsc6tj/file_stream\": unexpected EOF"}
{"time":"2025-08-06T19:08:44.939352-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.250.108.120:60722->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T19:09:07.6955742-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/tobiassafie-drexel-university/GBM-LSTM-lr-hiddenDim-dropout/dghsc6tj/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T19:09:08.3601603-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T19:09:33.449031-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/tobiassafie-drexel-university/GBM-LSTM-lr-hiddenDim-dropout/dghsc6tj/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T19:09:33.9961366-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T19:10:03.9368567-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/tobiassafie-drexel-university/GBM-LSTM-lr-hiddenDim-dropout/dghsc6tj/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T19:10:04.8760412-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
