{"time":"2025-08-06T18:00:49.0732303-04:00","level":"INFO","msg":"stream: starting","core version":"0.21.0"}
{"time":"2025-08-06T18:00:49.2663673-04:00","level":"INFO","msg":"stream: created new stream","id":"nja14a07"}
{"time":"2025-08-06T18:00:49.2663673-04:00","level":"INFO","msg":"stream: started","id":"nja14a07"}
{"time":"2025-08-06T18:00:49.2663673-04:00","level":"INFO","msg":"handler: started","stream_id":"nja14a07"}
{"time":"2025-08-06T18:00:49.2663673-04:00","level":"INFO","msg":"sender: started","stream_id":"nja14a07"}
{"time":"2025-08-06T18:00:49.2663673-04:00","level":"INFO","msg":"writer: Do: started","stream_id":"nja14a07"}
{"time":"2025-08-06T18:06:24.2783825-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.250.108.120:53649->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T18:06:43.9888608-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/tobiassafie-drexel-university/GBM-LSTM-lr-hiddenDim-dropout/nja14a07/file_stream\": read tcp 10.250.108.120:53774->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T18:06:48.2766198-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T18:07:23.0766474-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
{"time":"2025-08-06T18:07:23.8952063-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/tobiassafie-drexel-university/GBM-LSTM-lr-hiddenDim-dropout/nja14a07/file_stream\": read tcp 10.250.108.120:53685->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T18:07:49.7770343-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/tobiassafie-drexel-university/GBM-LSTM-lr-hiddenDim-dropout/nja14a07/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T18:07:53.2423052-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T18:08:19.3329846-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/tobiassafie-drexel-university/GBM-LSTM-lr-hiddenDim-dropout/nja14a07/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-06T18:08:31.5014564-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
